"""rebuild flights schema

Revision ID: 2e9cb0cadf86
Revises: 
Create Date: 2026-01-18 08:30:29.044978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e9cb0cadf86'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_name', sa.String(length=255), nullable=True),
    sa.Column('trip_id', sa.String(length=64), nullable=True),
    sa.Column('trip_type', sa.String(length=64), nullable=True),
    sa.Column('activity_id', sa.String(length=64), nullable=True),
    sa.Column('activity_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('booking_site', sa.String(length=255), nullable=True),
    sa.Column('supplier_confirmation', sa.String(length=128), nullable=True),
    sa.Column('booking_date', sa.Date(), nullable=True),
    sa.Column('booking_site_phone', sa.String(length=64), nullable=True),
    sa.Column('traveller', sa.String(length=128), nullable=True),
    sa.Column('ticket_number', sa.String(length=64), nullable=True),
    sa.Column('airline_code', sa.String(length=16), nullable=True),
    sa.Column('aircraft', sa.String(length=64), nullable=True),
    sa.Column('service_class', sa.String(length=64), nullable=True),
    sa.Column('flight_number', sa.String(length=32), nullable=True),
    sa.Column('start_country', sa.String(length=128), nullable=True),
    sa.Column('start_city_name', sa.String(length=128), nullable=True),
    sa.Column('start_airport', sa.String(length=64), nullable=True),
    sa.Column('start_terminal', sa.String(length=32), nullable=True),
    sa.Column('start_lat', sa.Float(), nullable=True),
    sa.Column('start_long', sa.Float(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_country', sa.String(length=128), nullable=True),
    sa.Column('end_city_name', sa.String(length=128), nullable=True),
    sa.Column('end_airport', sa.String(length=64), nullable=True),
    sa.Column('end_terminal', sa.String(length=32), nullable=True),
    sa.Column('end_lat', sa.Float(), nullable=True),
    sa.Column('end_long', sa.Float(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('stops', sa.Integer(), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flight')
    # ### end Alembic commands ###
