"""Add achievement_badge table

Revision ID: ff009e206c28
Revises: f0f0f0f0f0f0
Create Date: 2026-02-04 22:20:07.079132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff009e206c28'
down_revision = 'f0f0f0f0f0f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievement_badge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('badge_type', sa.String(length=64), nullable=False),
    sa.Column('threshold_value', sa.Integer(), nullable=False),
    sa.Column('icon_emoji', sa.String(length=8), nullable=True),
    sa.Column('icon_url', sa.String(length=255), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('flight_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flight_history_dep_date'))
        batch_op.drop_index(batch_op.f('ix_flight_history_flight_id'))

    with op.batch_alter_table('flight_history_air_nav_radar', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flight_history_air_nav_radar_dep_date'))
        batch_op.drop_index(batch_op.f('ix_flight_history_air_nav_radar_flight_id'))

    with op.batch_alter_table('flight_position', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flight_position_history_id'))
        batch_op.drop_index(batch_op.f('ix_flight_position_position_updated'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flight_position', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flight_position_position_updated'), ['position_updated'], unique=False)
        batch_op.create_index(batch_op.f('ix_flight_position_history_id'), ['history_id'], unique=False)

    with op.batch_alter_table('flight_history_air_nav_radar', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flight_history_air_nav_radar_flight_id'), ['flight_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_flight_history_air_nav_radar_dep_date'), ['dep_date'], unique=False)

    with op.batch_alter_table('flight_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flight_history_flight_id'), ['flight_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_flight_history_dep_date'), ['dep_date'], unique=False)

    op.drop_table('achievement_badge')
    # ### end Alembic commands ###
